#!/bin/bash

# screenshot current screen
scrot /tmp/screen.png

# blur
convert /tmp/screen.png -paint 1 -swirl 360 /tmp/screen.png

# add lock to image
[[ -f "$HOME/.i3/lock/lock.png" ]] && convert /tmp/screen.png  "$HOME/.i3/lock/lock.png" -gravity center -composite -matte /tmp/screen.png

# pause music
mocp -P
mpc pause

# lock the screen
i3lock -u -e -i /tmp/screen.png

# check if still locked after 20 seconds and turn off screen
sleep 20 && pgrep i3lock && xset dpms force off

