---
  language: go
  sudo: true
  notifications:
    emai: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet main.go
    - staticcheck main.go
    - golint -set_exit_status main.go
    - go test -v
