---
  language: go
  sudo: true
  notifications:
    emai: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get -u -v github.com/golang/lint/golint honnef.co/go/tools/cmd/staticcheck github.com/mitchellh/go-homedir github.com/sirupsen/logrus github.com/tcnksm/go-input
  script:
    - go build -v
    - go vet main.go
    - staticcheck main.go
    - golint -set_exit_status main.go
    - go test -v
