#!/bin/bash

# check if we have brew installed, else install it
if ! type brew &> /dev/null; then
    echo "Installing Homebrew.."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# upgrade & update before starting
brew update
brew upgrade

# install applications
brew install brew-cask-completion \
    coreutils \
    ctags \
    curl \
    dialog \
    ffmpeg \
    findutils \
    fzf \
    git \
    gnupg \
    go \
    hopenpgp-tools \
    htop \
    imagemagick \
    jq \
    moreutils \
    node \
    perl \
    pinentry-mac \
    python3 \
    ripgrep \
    shellcheck \
    sqlite \
    tmux \
    tree \
    vim \
    watch \
    wget \
    ykman \
    youtube-dl \
    yubikey-personalization  \
    zsh

exit 0
