#!/bin/bash
brew tap caskroom/cask

# install applications
brew cask install alfred \
    battle-net \
    captain \
    contexts \
    docker \
    fing \
    flux \
    google-chrome-dev \
    iterm2 \
    postman \
    signal \
    slack \
    spectacle \
    spotify \
    sublime-text \
    tunnelblick \
    vlc

exit 0
