#!/bin/bash
brew tap homebrew/cask-cask

# install applications
brew cask install alfred \
    battle-net \
    contexts \
    docker \
    fing \
    iterm2 \
    postman \
    signal \
    slack \
    spectacle \
    spotify \
    tunnelblick \
    vlc

exit 0
