#!/bin/bash
alias cat="bat"
alias du="dust"
alias find="fd"
alias ls="lsd"
alias top='ytop'

alias python="python3"
alias httpserver="python3 -m http.server"
alias tardown="tar -zxf"
alias tarup="tar -zcf"
alias usystemctl="systemctl --user"
alias backup="/usr/local/bin/rsync_tmbackup.sh"
alias ap='ansible-playbook'

alias xrdb='xrdb -load ~/.config/X11/xresources'

