#!/bin/bash

# --- generally useful ---
alias ..='cd ..'
alias l='ls -lFh'
alias la='ls -lAFh'
alias lr='ls -tRFh'
alias lt='ls -ltFh'
alias ll='ls -l'
alias ldot='ls -ld .*'
alias lS='ls -1FSsh'
alias lart='ls -1Fcart'
alias lrt='ls -1Fcrt'
alias grep='grep --color=auto'
alias vi='vim'
alias tarup='tar -zcf'
alias tardown='tar -zxf'
alias update='sudo apt update; sudo apt upgrade -y'
alias shutdown='sudo shutdown now'
alias restart='sudo shutdown -r now'
alias listcron='sudo $HOME/.bin/listcron'
alias listservicespi='service --status-all | grep +'
alias listservices='sudo systemctl -r --type service --all | grep " active"'
alias mpack='makepkg -s'
alias ipack='makepkg -i'
alias cupdate='find .-name PKGBUILD -execdir makepkg -si \;'

# --- dotfile shortcuts ---
alias zshrc='$EDITOR ~/.zshrc'
alias i3config='$EDITOR ~/.i3/config'
alias terminalrc='$EDITOR $HOME/.config/xfce4/terminal/terminalrc'
alias htoprc='$EDITOR $HOME/.config/htop/htoprc'
alias vimrc='$EDITOR ~/.vimrc'
alias sshconfig='$EDITOR ~/.ssh/config'
alias vimupdate='vim +PluginInstall +qall'

# --- git ---
alias gs='git status'
alias gaa='git add --all'
alias gap='git add --patch'
alias gpull='git pull'

# --- npm && yarn ---
alias y='yarn'
alias n='npm'

# --- tmux ---
alias tl='tmux list-sessions'

# --- docker ---
source "$HOME/.docker/docker.alias"

# --- misc ---
alias starttorrent='deluged; deluge-web&;'
alias stoptorrent='pkill deluge; pkill deluged; pkill deluge-web;'
alias airvpn='sudo openvpn --config --mute-replay-warnings $HOME/vpn/AirVPN_United-Kingdom_UDP-443.ovpn'
alias scp='sftp -P 999'
alias sftp='sftp -P 999'
alias checkip='curl icanhazip.com'
alias src='source ~/.zshrc'
alias pls='sudo $(fc -ln -1)'
alias irc='weechat'
alias weather='curl wttr.in/Edinburgh'
alias wtf='dmesg | tail'

# --- python ---
alias vv='virtualenv venv'
alias svenv='source ./venv/bin/activate'
alias preqs='pip freeze > requirements.txt'

# --- arch specific ---
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDF_VTNR" -eq 1 ]; then
    exec startx
fi

if [ "$HOST" = "archie" ] || [ "$HOST" = "glados" ]; then
   /opt/vc/bin/tvservice -o 
fi
