#!/bin/bash

if [ "$(uname -s)" == "Darwin" ]
then
    export ZSH=/Users/$USER/.oh-my-zsh
else
    export ZSH=/home/$USER/.oh-my-zsh
fi

export ZSH_THEME=afowler
plugins=(git nvm history jump extract gitignore)
export VISUAL=vim
export EDITOR=vim
export TERM=xterm-256color
export CLICOLOR=1
export GOPATH=~/projects/go
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/$USER/.bin:/home/$USER/bin"
export PATH=$PATH:$GOPATH

# ignore certain things in history
export HISTIGNORE=" *:ls:cd:cd -:pwd:exit:date:* --help:* ";

# project exports
export SPOTIPY_CLIENT_ID='ea8316fa93a740ad99f6e773bfedb2da'
export SPOTIPY_REDIRECT_URI='http://localhost/listentothis/callback/'
