#!/bin/bash

export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME=spaceship
SPACESHIP_DOCKER_SHOW=false
# shellcheck disable=SC2034
plugins=(git nvm history jump extract gitignore)
export VISUAL=vim
export EDITOR=vim
export TERM=xterm-256color
export CLICOLOR=1
export GOPATH="$HOME"/go
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$HOME/.bin:$HOME/bin:$HOME/.scripts"
export PATH=$PATH:$GOPATH
export HISTORIAN_SRC="$HOME"/.zsh_history

# ignore certain things in history
export HISTIGNORE=" *:ls:cd:cd -:pwd:exit:date:* --help:* ";

# project exports
export SPOTIPY_CLIENT_ID='ea8316fa93a740ad99f6e773bfedb2da'
export SPOTIPY_REDIRECT_URI='http://localhost/listentothis/callback/'
