#!/bin/bash

# oh-my-zsh
source "$ZSH"/oh-my-zsh.sh

# base16 shell
export BASE16_SHELL="$HOME/.config/base16-shell/base16-ocean.dark.sh"
[[ -s $BASE16_SHELL ]] && source "$BASE16_SHELL"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# source cargo for rust
[ -f "$HOME"/.cargo/env ] && source "$HOME"/.cargo/env

# import shell history into historian if it exists
[ -f "$HOME"/historian/hist ] && hist import &> /dev/null

source $HOME/google-cloud-sdk/completion.zsh.inc
source $HOME/google-cloud-sdk/path.zsh.inc

