#!/bin/bash

# shellcheck disable=SC2034
plugins=(git npm history pip brew docker zsh-autosuggestions)

setopt correct              # command auto-correction
setopt correctall           # argument auto-correction
setopt histignorealldups    # filter duplicates from history

zle -N fg-bg                # function from ../functions
bindkey '^Z' fg-bg

