#!/bin/bash

choices="x220\\nx220&144hz\\n144hz\\nmanual"
chosen=$(echo -e "$choices" | dmenu -i)

case "$chosen" in
  x220) ~/.screenlayout/x220.sh;;
  x220\&144hz) ~/.screenlayout/home-laptop-144.sh;;
  144hz) ~/.screenlayout/home-144.sh;;
  manual) arandr && ~/.config/polybar/launch.sh
esac

