#!/bin/bash
# Script to add a user to Linux system
if [ "$(id -u)" -eq 0 ]; then
    echo "Enter username: "
    read -r username
    echo "Enter password: "
    read -rs password
    egrep "^$username" /etc/passwd >/dev/null && echo -e "\n$username already exists" && exit 1

    pass=$(perl -e 'print crypt($ARGV[0], "password")' "$password")
    useradd -m -p "$pass" "$username" && echo -e "\nUser successfully added" || echo -e "\nFailed to add user"
else
    echo "script must be run as root"
    exit 2
fi
