#!/bin/bash
figlet -f big "$(hostname -s)"
awk -v date="$(date +"%a %b %d %r %Z")" \
    -v hostname="$(hostname)" \
    -v external_ip="$(curl -s checkip.amazonaws.com)" \
    -v internal_ip="$(ip r | awk 'NR==2{print $9}')" \
    -v release="$(lsb_release -d |  awk '{ print $2, $3 }')" \
    -v name="$(lsb_release -c |  awk '{ print $2 }')" \
    -v loadavg="$(uptime | awk '{print $10, $11, $12}')" \
    -v uptime="$(uptime -p | sed 's/up //')" \
    -v kernel="$(uname -rp)" \
    -v cpu_usage="$(top -bn 1 | awk 'NR==3{print 100-$8}')" \
    -v free_memory="$(free -h | awk 'NR==2{print $4}')" \
    -v free_cache="$(free -h | awk 'NR==3{print $4}')" \
    -v disk_used="$(df -H --total | awk 'END { printf "%s %s %3s (%s)\n", $3, "/", $2, $5 }')" \
    -v format="%s %-25s %s %s\\n" \
    -v extra="%s %-25s %s %s %s\\n" \
    'BEGIN { 
            print "Status:"
            print date
            printf format, "-", "Name", "=", hostname
            printf format, "-", "External IP", "=", external_ip
            printf format, "-", "Internal IP(s)", "=", internal_ip
            printf format2, "-", "OS Version", "=", release, name
            printf format, "-", "Kernel", "=", kernel
            printf format, "-", "System Uptime", "=", uptime
            printf format, "-", "Load Averages", "=", loadavg
            printf "%s %-25s %s %s%s\n", "-", "CPU Usage (average)", "=", cpu_usage, "%"
            printf format, "-", "Free Memory (Real)", "=", free_memory
            printf format, "-", "Free Memory (Cache)", "=", free_cache
            printf format, "-", "Disk used", "=", disk_used
           }'

printf "  " && printf "%0.s-" {1..43} && printf "\\n"

echo
