#!/bin/bash
set -e
set -o pipefail

if [ "$1" ]; then
    shellcheck "$1" && echo "[OK]: successfully linted $1"
    exit 0
fi

(
# find all executables and run `shellcheck`
for f in $(find . -type f -not -iwholename '*.git*' | sort -u); do
	if file "$f" | grep --quiet shell; then
		shellcheck "$f" && echo "[OK]: sucessfully linted $f"
	fi
done
)
