#!/bin/bash
set -e
set -o pipefail

ERRORS=()

while IFS= read -r -d '' f
do
  if file "$f" | grep --quiet shell; then
  {
    shellcheck "$f" && echo "[OK]: successfully linted $f"
  } || {
    ERRORS+=("$f")
  }
  fi
done < <(find config.sym/sh-utils bin.sym -type f -print0)

if [ ${#ERRORS[@]} -eq 0 ]; then
	echo "No errors!"
else
	echo "These files failed shellcheck: ${ERRORS[*]}"
	exit 1
fi
