---
- hosts: 127.0.0.1
  connection: local
  user: root
  tasks:

  - name: install zsh, git, & vim
    apt: pkg=zsh,git,vim state=latest
    register: pkgs_installed

  - name: create user
    when: pkgs_installed|success
    user:
      name=wilkins
      groups=sudo
      append=yes
      shell=/bin/zsh
    register: user_created

  - name: clone oh-my-zsh
    when: user_created|success
    become_user: wilkins
    become: true
    git:
      repo=https://github.com/robbyrussell/oh-my-zsh
      dest=~/.oh-my-zsh
    register: ohmyzsh_cloned

  - name: make sure ~/.vim exists
    become_user: wilkins
    become: true
    file:
      path: ~/.vim
      state: directory
    register: vim_dir_exists

  - name: make sure ~/.vim/bundle exists
    when: vim_dir_exists|success
    become_user: wilkins
    become: true
    file:
      path: ~/.vim/bundle
      state: directory
    register: bundle_exists

  - name: clone vundle
    when: bundle_exists|success
    become_user: wilkins
    become: true
    git:
      repo=https://github.com/VundleVim/Vundle.vim
      dest=~/.vim/bundle/Vundle.vim
    register: vundle_installed

  - name: download dotfiles
    become_user: wilkins
    become: true
    git:
      repo=https://github.com/W1lkins/dotfiles
      dest=~/dotfiles
    register: dotfiles_cloned

  - name: chmod bootstrap
    when: dotfiles_cloned|success
    become_user: wilkins
    become: true
    file:
      path: ~/dotfiles/bootstrap.sh
      mode: 0755
    register: bootstrap_ready

    #  - name: run bootstrap.sh from dotfiles
    #    when: bootstrap_ready|success
    #    become_user: wilkins
    #    become: true
    #    script: ~/dotfiles/bootstrap.sh
