#!/bin/bash
# Requires:
# 1password CLI - https://app-updates.agilebits.com/product_history/CLI
# jq - https://stedolan.github.io/jq/

1passlogin() {
    eval "$(op signin my)"
}

1pass() {
    op get item "$1" | jq '.details.fields[1].value' | sed s/\"//g
}

