#!/bin/bash

dots() {
  cd "$HOME/dotfiles" || exit 1
}

zshrc() {
  $EDITOR ~/.zshrc
}

i3config() {
  $EDITOR ~/.i3/config
}

terminalrc() {
  $EDITOR "$HOME/.config/xfce4/terminal/terminalrc"
}

htoprc() {
  $EDITOR "$HOME/.config/htop/htoprc"
}

vimrc() {
  $EDITOR "$HOME/dotfiles/vimrc.sym"
}

sshconfig() {
  $EDITOR "$HOME/.ssh/config"
}

scripts() {
  cd "$HOME/.scripts" || exit 1
}

vimplugins() {
  cd "$HOME/.vim/bundle" || exit 1
}

tmuxconf() {
  $EDITOR "$HOME/.tmux.conf"
}

