#!/bin/bash

dots() {
    cd -q "$HOME/workspace/github.com/w1lkins/dotfiles" 2>/dev/null ||
        cd "$HOME/dotfiles" 2>/dev/null ||
        return
}

zshrc() {
    $EDITOR "$HOME/.zshrc"
}

i3config() {
    $EDITOR "$HOME/.i3/config"
}

htoprc() {
    $EDITOR "$HOME/.config/htop/htoprc"
}

vimrc() {
    $EDITOR ~/.vimrc
}

sshconfig() {
    $EDITOR "$HOME/.ssh/config"
}

scripts() {
    cd "$HOME/.scripts" || return
}

vimplugins() {
    cd "$HOME/.vim/bundle" || return
}

tmuxconf() {
    $EDITOR "$HOME/.tmux.conf"
}

