#!/bin/bash

# restart gpg-agent
resgpg() {
    sudo pkill -9 gpg-agent && gpg-connect-agent reloadagent /bye
}

# list secret gpg keys
gpglist() {
    gpg --list-keys --keyid-format LONG
}

# encrypt with gpg
gpgencrypt() {
    gpg -r jonathan@wilkins.tech -e "$1"
}

# decrypt with gpg
gpgdecrypt() {
    gpg -d "$1"
}

# import keys
gpgimport() {
    gpg --allow-secret-key-import --import "$1"
}

gpgexport() {
    gpg --armor --export "$1"
}

