#!/bin/bash

# set the system profile theme to day or night mode
setprof() {
  # do things differently on osx and linux
  if [[ $(findcurrentos) == "OSX" ]]; then
    # set the iTerm theme
    echo -e "\\033]50;SetProfile=$1\\a";

    # set dock and menubar theme
    if [[ "$1" == "day" ]]; then
      osascript -e 'tell application "System Events"
      tell appearance preferences to set dark mode to false
      end tell'
    else
      osascript -e 'tell application "System Events"
      tell appearance preferences to set dark mode to true
      end tell'
    fi
  else
    echo "Not implemented for non-OSX systems yet!"
  fi
}

cdfinder() {
  cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')" || exit 1
}

showfiles() {
  defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder
}

hidefiles() {
  defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder
}

