#!/bin/bash

function starttorrent() {
  deluged; deluge-web&;
}

function stoptorrent() {
  pkill deluge; pkill deluged; pkill deluge-web;
}

function checkip() {
  curl icanhazip.com
}

function src() {
  source ~/.zshrc
}

function pls() {
  sudo $(fc -ln -1)
}

function irc() {
  weechat
}

function weather() {
  curl wttr.in/Edinburgh
}

function hist() {
  "$HOME"/historian/hist
}

function wtf() {
  dmesg | tail
}

# Make CTRL-Z background things and unbackground them.
function fg-bg() {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
  else
    zle push-input
  fi
}

