#!/bin/bash
# shellcheck source=/dev/null

starttorrent() {
  deluged && deluge-web&
}

stoptorrent() {
  pkill deluge; pkill deluged; pkill deluge-web;
}

checkip() {
  curl icanhazip.com
}

src() {
  source ~/.zshrc
}

pls() {
  sudo "$(fc -ln -1)"
}

irc() {
  weechat
}

weather() {
  curl wttr.in/Edinburgh
}

wtf() {
  dmesg | tail
}

# Make CTRL-Z background things and unbackground them.
fg-bg() {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
  else
    zle push-input
  fi
}

pb() {
  curl -F "c=@${1:--}" "https://p.wilkins.cloud/?u=1";
}

