#!/bin/bash
# shellcheck source=/dev/null

function simpleserver() {
  python3 -m http.server
}

function vv() {
  pipenv install
}

function svenv() {
  pipenv shell
}

function preqs() {
  pip freeze > requirements.txt
}

