#!/bin/bash

alias ..='cd ..'
alias l='ls -lFh'
alias la='ls -lAFh'
alias lr='ls -tRFh'
alias lt='ls -ltFh'
alias ll='ls -l'
alias ldot='ls -ld .*'
alias lS='ls -1FSsh'
alias lart='ls -1Fcart'
alias lrt='ls -1Fcrt'
alias vi='$EDITOR'
alias tarup='tar -zcf'
alias tardown='tar -zxf'
alias shutdown='sudo shutdown now'
alias restart='sudo shutdown -r now'
alias python=python3
alias vim=nvim
alias jk=jekyll
alias usystemctl='systemctl --user'

