#!/bin/bash

alias cat='$HOME/.cargo/bin/bat'
alias drive='gdrive'
alias httpserver='miniserve'
alias ls='$HOME/.cargo/bin/exa'
alias python=python3
alias tardown='tar -zxf'
alias tarup='tar -zcf'
alias usystemctl='systemctl --user'
alias vi='$EDITOR'
alias vim='nvim'

