#!/bin/bash

# Make sure we actually get passed in an arg ($1)
if [ $# -eq 0 ]
then
    echo "Error, no directory specified."
    exit 0
fi

# Set the first argument to the directory we're going to check
DIR_TO_CHECK=$1

# Get the path to the hidden old stat file
OLD_STAT_FILE="$1/.old_stat"
 
if [ -e "$OLD_STAT_FILE" ]
then
    OLD_STAT=$(cat "$OLD_STAT_FILE")
else
    OLD_STAT="nothing"
fi
 
NEW_STAT=$(stat -t "$DIR_TO_CHECK")
 
if [ "$OLD_STAT" != "$NEW_STAT" ]
then
    echo -e "Directory $1 has changed"
    # update the OLD_STAT_FILE
    echo "$NEW_STAT" > "$OLD_STAT_FILE"
fi
