#!/bin/bash
EXPORT_PUB_LOCATION="./mygpgkey_pub.gpg"
EXPORT_SEC_LOCATION="./mygpgkey_sec.gpg"

read -rp "Location for public key? (default: $EXPORT_PUB_LOCATION): " pub
[[ ! -z "$pub" ]] && EXPORT_PUB_LOCATION=$pub

read -rp "Location for secret key? (default: $EXPORT_SEC_LOCATION): " sec
[[ ! -z "$sec" ]] && EXPORT_SEC_LOCATION=$sec

echo -e "Listing keys...\\n"
gpg --list-keys | grep pub

echo ""
read -rp "Which key to export? " key
if [[ -z "$key" || ! "$key" =~ ^0x ]]; then
  echo "Doesn't look like a GPG key" && exit 1
fi

gpg --output "$EXPORT_PUB_LOCATION" --armor --export "$key" && \
gpg --output "$EXPORT_SEC_LOCATION" --armor --export-secret-key "$key"

