#!/bin/bash

program_name="$1"
program_path="$2"
icon_path="$3"

if [[ -n "$program_name" || -n "$program_path" || -n "$icon_path" ]]; then
    cat > "$program_name.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=$program_name
Terminal=true
Exec=$program_path
Icon=$icon_path
EOF
else
    echo -e "Missing param - Usage:\n- mkdesktopfile [program name] [path to program] [path to icon]"
fi
