#!/bin/bash
readonly POOL="sks-keyservers.net"

echo -e "Listing keys...\\n"
gpg --list-keys | grep pub

echo ""
read -rp "Which key to send? " key
if [[ -z "$key" || ! "$key" =~ ^0x ]]; then
  echo "Doesn't look like a GPG key" && exit 1
fi

gpg --keyserver "$POOL" --send-key "$key"

